services:
  postgres:
    image: postgres:15.2
    container_name: avantsoft-postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env.development
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
